version: "2.1"

services:
    php:
        build: .
        container_name: btc_ticker_php
        volumes:
            - ./docker/php.ini:/usr/local/etc/php/php.ini
            - .:/var/www/btc_ticker
        links:
            - redis:redis
        ports:
            - "8085:8085"
    nginx:
        image: nginx:1.9
        ports:
            - "8083:80"
        depends_on:
            - php
        volumes:
            - ./docker/site.conf:/etc/nginx/conf.d/site.conf
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
    redis:
        container_name: btc_ticker_redis
        image: redis:3
        ports:
            - "6379:6379"